config/routes.rb
Rails.application.routes.draw do
  resources :tweeets do
    collection do
       post :confirm
     end
   end
  root "tweeets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweeet.rb
class Tweeet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweeets_controller.rb
class TweeetsController < ApplicationController
  before_action :set_tweeet, only: %i[ show edit update destroy ]

  # GET /tweeets or /tweeets.json
  def index
    @tweeets = Tweeet.all
  end

  # GET /tweeets/1 or /tweeets/1.json
  def show
  end

  # GET /tweeets/new
  def new
    @tweeet = Tweeet.new
  end

  # GET /tweeets/1/edit
  def edit
  end

  # POST /tweeets or /tweeets.json
  def create
    @tweeet = Tweeet.new(tweeet_params)

    respond_to do |format|
      if @tweeet.save
        format.html { redirect_to @tweeet, notice: "Tweeet was successfully created." }
        format.json { render :show, status: :created, location: @tweeet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweeet.errors, status: :unprocessable_entity }
      end
    end
  end
  def confirm
    @tweeet = Tweeet.new(tweeet_params)
    render :new if @tweeet.invalid?
  end
  # PATCH/PUT /tweeets/1 or /tweeets/1.json
  def update
    respond_to do |format|
      if @tweeet.update(tweeet_params)
        format.html { redirect_to @tweeet, notice: "Tweeet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweeet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweeet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweeets/1 or /tweeets/1.json
  def destroy
    @tweeet.destroy
    respond_to do |format|
      format.html { redirect_to tweeets_url, notice: "Tweeet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweeet
      @tweeet = Tweeet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweeet_params
      params.require(:tweeet).permit(:tweeet, :title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweeets_helper.rb
module TweeetsHelper
    def choose_new_or_edit
        if action_name == 'new' || action_name == 'confirm' || action_name == 'create' || action_name =='show'
          confirm_tweeets_path
        elsif action_name == 'edit'
          tweeet_path
        end
      end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twittter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.main.css' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
    <div class="notification is-primary global-notification">
      <p class="notice"><%= notice %>
        </div>
        <% end %>
        <% if flash[:alert] %>
        <div class="notification is-danger global-notification">
          <p class="alert"><%= alert %></p>
          </div>
          <% end %>
          <nav class="navbar is-info">
            <div class="navbar-brand">
            <%= link_to root_path, class: "navbar-item" do %>
          <h1 class="title is-5">Twittter</h1>
          <% end %>
          <div class="navbar-burger burger" data-target="navbarExample">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>

    <div id="navbarExample" class="navbar-menu">
    <div class="navbar-end">
    <div class="field is-grouped">
    <p class="control">
    <% link_to 'New Tweeet', new_tweeet_path, class: "button is-info is-inverted" %>
  </p>


</div>
</div>
</div>
          </nav>
    <%= yield %>
  </body>
</html>

app/views/tweeets/_feed.html.erb
<div class="column is-half">
<article class="media box">
<figure class="media-left">
<p class="image is-64x64">
<img src="https://bulma.io/images/placeholders/64x64.png">
</p>
</figure>
<div class="media-content">

</div>
</article>
</div>

<@tweeets.each do | tweeet | %>
<div class="box">
<article class="media">
<div class="media-left">
<figure class="image is-64x64">
<img src="https://bulma.io/images/placeholders/64x64.png">
</figure>
<div class="media-content">
<div class="content">
<strong>Andy leverenz</strong><br/>
<p><%= tweeet.tweeet %></p>
</div>
<nav class="level">
<div class="level-left is-mobile">
<% link_to tweeet, class: "level-item" do %>
<span class="icon"><i class="fa fa-link" aria-hidden="true"></i></span>
<% end %>
<% link_to edit_tweeet_path(tweeet), class="level-item" do %>
<span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
  <% end %>
  <% link_to tweeet, method: :delete,data: { confirm: "are you sure you want to delete this tweet?"
} do %>
<span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
<% end %>
</div>
</nav>
</div>
</div>
</article>
</div>
<% end %>

app/views/tweeets/_form.html.erb
<%= form_with(model: @tweeet,local: true, url: choose_new_or_edit) do |form| %>
  <% if tweeet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweeet.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% tweeet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :tweet %>
    <%= form.text_area :tweeet %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tweeets/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Tweeet</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/tweeets/confirm.html.erb
<h3>Send with the following contents.</h3>
<%= form_with(model: @tweeet, url: tweeets_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :tweeet %>
  <p>title:<%= @tweeet.title %></p>
  <p>content:<%= @tweeet.tweeet %></p>
  <%= form.submit  "confirm" %>
  <%= link_to 'Back', new_tweeet_path %>
<% end %>

app/views/tweeets/edit.html.erb
<h1>Editing Tweeet</h1>

<%= render 'form', tweeet: @tweeet %>

<%= link_to 'Show', @tweeet %> |
<%= link_to 'Back', tweeets_path %>

app/views/tweeets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tweeets</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Tweeet</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweeets.each do |tweeet| %>
      <tr>
        <td><%= tweeet.title %></td>
        <td><%= tweeet.tweeet %></td>
        <td><%= link_to 'Show', tweeet %></td>
        <td><%= link_to 'Edit', edit_tweeet_path(tweeet) %></td>
        <td><%= link_to 'Destroy', tweeet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweeet', new_tweeet_path %>

app/views/tweeets/new.html.erb
<h1>New Tweeet</h1>

<%= render 'form', tweeet: @tweeet %>

<%= link_to 'Back', tweeets_path %>

app/views/tweeets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @tweeet.title %>
</p>
<p>
  <strong>Tweeet:</strong>
  <%= @tweeet.tweeet %>
</p>

<%= link_to 'Edit', edit_tweeet_path(@tweeet) %> |
<%= link_to 'Back', tweeets_path %>